name: beneficios-api
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint:
      - /bin/sh
      - -c
      - |
        cd /app
        php artisan key:generate
        exec php artisan serve --host="0.0.0.0" --port="8000"
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443" # Si planeas usar HTTPS
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
