version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    container_name: app
    ports:
      - "8000:8000"
    working_dir: /app
    entrypoint:
      - /bin/sh
      - -c
      - |
        php artisan key:generate
        exec php artisan serve --host="0.0.0.0" --port="8000"
  nginx:
    image: nginx:latest
    container_name: server
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
